#!/bin/bash

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

mpv /usr/share/sounds/freedesktop/stereo/dialog-information.oga
mpv /usr/share/sounds/freedesktop/stereo/dialog-information.oga
